INFO:root:RPC client connected - server_port=1234, server_ip='192.168.40.23', ssl=True
INFO:root:Console created - self.cid='1'
INFO:root:session created - 1
INFO:root:Meterpreter shell session created - diff={'2'}
INFO:root:unable to create session
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f94b98e6dc0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f94b993b430>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
