INFO:root:RPC client connected - server_port=1234, server_ip='192.168.40.23', ssl=True
INFO:root:Console created - self.cid='1'
INFO:root:using scan - scanner/portscan/tcp
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1b806f7100>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 1 seconds...
WARNING:retry.api:HTTPSConnectionPool(host='192.168.40.23', port=1234): Max retries exceeded with url: /api/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1b806f6b20>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 2 seconds...
